[package]
name = "aura-lex"
version = "0.1.0"
edition = "2024"

[dependencies]
aura-ast = { path = "../aura-ast" }
logos = { workspace = true }
miette = { workspace = true }
thiserror = { workspace = true }

